#!/bin/bash

# This script will call the consumer API (mobile API) and attempt to get an OAUTH token
# which it will then use to call the consumer API. It will then wait for the token to expire
# try again, fail, request a new token using the expiry token, then try again, and pass.

# load variable names
. api_config_variables

# load client_credentials
# the below file was generated by the script 'provision_consumer_app.sh'
. client_credentials

# Since there is no username/password in this Client Credentials flow, we just need to
# Authenticate using the client credentials first in order to obtain an access key.
#
# NOTE: There are no no refresh tokens issued in this flow, so the client must occur
# within the expires_in timeframe or it will fail.

echo calling client API as an a mobile client and passing:
echo
echo POST https://kong:8443/client/v1/oauth2/token
echo client_id=$MOB_CLIENT_ID
echo client_secret=$MOB_CLIENT_SECRET
echo scope=${SECURE_API_SCOPES[0]} #tells the system which APIs we want
echo

ACCESS_TOKEN_RESPONSE=$( http --form --verify=no POST https://kong:8443/client/v1/oauth2/token \
	grant_type=client_credentials \
	client_id=$MOB_CLIENT_ID \
	client_secret=$MOB_CLIENT_SECRET \
	scope=${SECURE_API_SCOPES[0]} )

ACCESS_TOKEN=$(echo $ACCESS_TOKEN_RESPONSE | jq '.access_token' -r)
REFRESH_TOKEN=$(echo $ACCESS_TOKEN_RESPONSE | jq '.refresh_token' -r) #should return null
TOKEN_TYPE=$(echo $ACCESS_TOKEN_RESPONSE | jq '.token_type' -r)
EXPIRES_IN=$(echo $ACCESS_TOKEN_RESPONSE | jq '.expires_in' -r)

echo Got the following data from the request for a token
echo Note, there is no refresh token for a client Credentials Grant\!
echo access_token: $ACCESS_TOKEN
echo refresh_token: $REFRESH_TOKEN
echo token_type: $TOKEN_TYPE
echo expires_in: $EXPIRES_IN
echo

echo Now that we have client credentials, we call the newuser endpoint to create a new
echo user.

echo Now calling the API with the token just received.
http --verify=no --print HBhb POST https://kong:8443/client/v1/newuser \
	Authorization:"Bearer $ACCESS_TOKEN" \
	username=$AUTH_USERNAME \
	password=$AUTH_PASSWORD
