#!/bin/bash

# This script will call the consumer API (mobile API) and attempt to get an OAUTH token
# which it will then use to call the consumer API

# load variable names
. api_config_variables

# load provision keys for each API
# the below file was generated by the script 'load_oauth2_plugins_and_obtain_provision_keys.sh'
. provision_keys

# load client_credentials
# the below file was generated by the script 'provision_consumer_app.sh'
. client_credentials

# now call the public kong interface to request a token as if I am a client/sdk app
# NOTE client_* parameters would have been previously provided to this custoemr
# username/password would have been created by the end user in the sign-up use case.
# for this I am checking the credentials are correct in WireMock.
# See the wiremock mountpoint at wiremock:/mappings/user_authenticate_*.json

echo calling authentication API as an end user and passing:
echo
echo POST https://kong:8443/v1.0/authenticate
echo client_id=$MOB_CLIENT_ID
echo client_secret=$MOB_CLIENT_SECRET
echo username=$AUTH_USERNAME
echo password=$AUTH_PASSWORD

CLIENT_REQUEST=$( http --verify=no POST https://kong:8443/v1.0/authenticate \
	client_id=$MOB_CLIENT_ID \
	client_secret=$MOB_CLIENT_SECRET \
	username=$AUTH_USERNAME \
	password=$AUTH_PASSWORD )

echo

if [ $(echo $CLIENT_REQUEST | grep -c "Successfully authenticated") -eq 1 ]; then
	#successful authentication
	echo STATUS:success
else
	#failed authentication
	echo STATUS:failure
	exit 1
fi

# Ordinarily the Authenication server would make a call to Kong *before* responding to the
# Client application. This is as documented here:
# https://getkong.org/plugins/oauth2-authentication/#resource-owner-password-credentials.
# However, wiremock can't do that, so the below call is made to show the call that the
# Authentication Service would make at that point. From the Kong docs:

	# The backend of your web-application will authenticate the username and password
	# sent by the client, and if successful will add the provision_key and
	# authenticated_userid parameters to the parameters originally sent by the client,
	# and it will make a POST request to Kong at your API address, on the
	# /oauth2/token endpoint. If an Authorization header has been sent by the client,
	# that must be added too.

# Note that body of this post is not JSON, but standard application/x-www-form-urlencoded
# data. It must be this way as the RFC requires and Kong only responses to the request
# in this format.

#Note also that the specific API must be invoked and the provision_key used must be the one
# associated with that specific API.

echo Now calling the /oauth2/token endpoint of a specific API on Kong to get an oauth token
echo POST https://kong:8443/consumer/v1.0/oauth2/token
echo grant_type=password
echo client_id=$MOB_CLIENT_ID
echo client_secret=$MOB_CLIENT_SECRET
echo username=$AUTH_USERNAME
echo password=$AUTH_PASSWORD
echo provision_key=$consumer_api_v1_0_KEY
echo authenticated_userid=$AUTH_USERNAME
echo
echo
echo Please refer to the code comments for more information.


ACCESS_TOKEN_RESPONSE=$( http --form --verify=no POST https://kong:8443/consumer/v1.0/oauth2/token \
	grant_type=password \
	client_id=$MOB_CLIENT_ID \
	client_secret=$MOB_CLIENT_SECRET \
	username=$AUTH_USERNAME \
	password=$AUTH_PASSWORD \
	provision_key=$consumer_api_v1_0_KEY \
	authenticated_userid=$AUTH_USERNAME )

ACCESS_TOKEN=$(echo $ACCESS_TOKEN_RESPONSE | jq '.access_token' -r)
REFRESH_TOKEN=$(echo $ACCESS_TOKEN_RESPONSE | jq '.refresh_token' -r)
TOKEN_TYPE=$(echo $ACCESS_TOKEN_RESPONSE | jq '.token_type' -r)
EXPIRES_IN=$(echo $ACCESS_TOKEN_RESPONSE | jq '.expires_in' -r)

echo Got the following data from the request for a token
echo access_token: $ACCESS_TOKEN
echo refresh_token: $REFRESH_TOKEN
echo token_type: $TOKEN_TYPE
echo expires_in: $EXPIRES_IN
echo

# Now that we have a token, this response body should be sent back to the requester as a  response to the
# first HTTP Request in this script file.

# the below call makes the call again, from the perspective of the Client app (or SDK) on the assumption
# that this data was successfully sent back to the client.
echo Now calling the API with the token just received.
http --verify=no --print HBhb GET https://kong:8443/consumer/v1.0/hello.json \
	Authorization:"Bearer $ACCESS_TOKEN" \
