FROM bradqwood/wiremock
# a fork of rodolpheche/wiremock
MAINTAINER Bradley Wood <docker@bradleywood.com>
EXPOSE 8080
EXPOSE 8081
#users a local filesystem mountpoint that is set up using docker-compose, not here.  mounts to /home/wiremock
VOLUME /home/wiremock
WORKDIR /home/wiremock
